### ISSUE TITLE
Document required git (and svn?) versions?

### ISSUE THREAD

**Issue by billsacks** [ESCOMP/cesm#10]
@cecilehannay ran into trouble trying to checkout CESM using the instructions when using yellowstone. It turns out that the out-of-the-box git version on yellowstone is 1.7.1, but there are issues trying to fetch cime with this old git version. This is not related to manage_externals: even doing a manual git clone / git fetch leads to this issue:

First, when cloning:

```
$ git clone https://github.com/CESM-Development/cime
Initialized empty Git repository in /glade/p/work/sacks/temporary/cime/.git/
remote: Counting objects: 87692, done.
remote: Total 87692 (delta 0), reused 0 (delta 0), pack-reused 87692
Receiving objects: 100% (87692/87692), 33.18 MiB | 18.91 MiB/s, done.
Resolving deltas: 100% (64250/64250), done.
error: refs/tags/cime0_1_0 does not point to a valid object!
error: refs/tags/cime0.3.2 does not point to a valid object!
error: refs/tags/cime0.3.1 does not point to a valid object!
error: refs/tags/cime0.2.3 does not point to a valid object!
error: refs/tags/cime0.2.2 does not point to a valid object!
error: refs/tags/cime0.2.1 does not point to a valid object!
error: refs/tags/cime0.2.0 does not point to a valid object!
```

Then, when fetching:

```
$ git fetch origin
remote: Counting objects: 14, done.
remote: Total 14 (delta 1), reused 1 (delta 1), pack-reused 13
Unpacking objects: 100% (14/14), done.
error: unable to find 5fef7ed2dc848bda2aa3c106a77ba0a008ca858f
fatal: object 5fef7ed2dc848bda2aa3c106a77ba0a008ca858f not found
```

The error in fetching leads checkout_externals to abort.

yellowstone will be going away before this git-based version sees wide use. But should we document somewhere that a newer git version is needed? Version 1.8.3.1 (on hobart) works for me, so it appears that we need version 1.8 or later. Where should this documentation go?

I'm not sure if there are requirements for svn, or if any reasonable svn version should work.

**Comment by bandre-ucar** [comment]
See also: https://github.com/NCAR/manage_externals/issues/21

**Comment by billsacks** [comment]
Thanks @bandre-ucar I knew I had seen that somewhere, but couldn't remember where.

I'll close this issue given the existence of the other one, and the hope that this won't tend to bite us in practice once yellowstone goes away.
