### ISSUE TITLE
Test

### ISSUE THREAD

**Issue by jedwards4b** [ESCOMP/CESM#118]
Please ignore this issue - testing connection to slack

**Comment by jedwards4b** [comment]
This github repo is now connected to slack at [cesm2.slack.com](https://cesm2.slack.com) # github 
please join us there if like slack or want to learn more.

**Comment by jedwards4b** [comment]
This github repo is now connected to slack at cesm2.slack.com # github
please join us there if like slack or want to learn more.

**Comment by billsacks** [comment]
Closing this test issue.
