### ISSUE TITLE
Document ssh vs https for git repositories

### ISSUE THREAD

**Issue by bandre-ucar** [ESCOMP/cesm#12]
### Summary of Issue:

By default cesm is pointing to https urls for git repositories. This is fine for reading public repositories, but requires the user to input their github password many times for private repos.

### Expected behavior and actual behavior:

Document the recommended use and setup of ssh keys for accessing private forks.

**Comment by bandre-ucar** [comment]
See also: https://github.com/NCAR/manage_externals/issues/9

https://help.github.com/articles/connecting-to-github-with-ssh/

**Comment by bandre-ucar** [comment]
I'm not really sure how what needs to be said about this. My proposed text
```
Developer setup
===============

Developers who have not already done so should follow the recommended
[one-time](https://github.com/esmci/cime/wiki/CIME-Git-Workflow#configure-git-one-time)
setup directions for git. Developers may also want to set up
(ssh)[https://help.github.com/articles/connecting-to-github-with-ssh/]
keys and switch to using the `git@github.com:ESCOMP/cesm.git` form of the github URLs.

```
Should this go in the wiki or readme?

**Comment by bertinia** [comment]
my vote is at the end of the README.md
