### ISSUE TITLE
notifications to CESM developers when new tags are available

### ISSUE THREAD

**Issue by bertinia** [ESCOMP/cesm#13]
### Summary of Issue:
Currently, when new tags are created on the NCAR SVN server, an automated email is sent to 
a couple of different email lists; cgd-cseg for alpha tags and cesm-dev mailman account for
beta and release tags. The automated email is sent from a perl script that runs as a nightly cron job on the NCAR SVN server. 

How do we want to handle tag update notifications from this github repo? Should we encourage users and developers to setup a personal github account and manage their notifications /watches or do we need a script that sends notifications similar to what we currently have for SVN?

**Comment by billsacks** [comment]
Good question. As far as I know, watching a github repo will not notify you when a tag is made, although according to https://help.github.com/articles/about-notifications/ you can get notified when a _Release_ is created on github. However, you can't sign up to _just_ get notified when a release is created - so anyone signing up for that will be spammed with the more frequent traffic of issues, PRs, etc. I don't know what the answer is here.

See also https://github.com/isaacs/github/issues/410

**Comment by fischer-ncar** [comment]
I think it should be possible to modify our current scripts to watch of github releases.

**Comment by bertinia** [comment]
Technically, @fischer-ncar is correct. But, I think we should encourage
our users to be proactive in managing their notifications via github rather than relying on NCAR
to send out updates to mailman lists that aren't currently being maintained. This places the
onus on users as to whether or not they want to be notified of issues and updates for this repo. 
We can instruct users on how to setup their "watch" preferences via the forums and a web page with the general CESM github instructions.

**Comment by cacraigucar** [comment]
If you can figure out a way to document how users can receive notifications **ONLY** when a tag is made and a summary of what is new in that tag, then I'm OK with that.  If their only option is to also see all PR and issues that are on that repo, then this is too much information for anyone other than active developers on the repo.  Most users only want to know the "summary" results like in our current ChangeLog for tags and not the back and forth discussions and intricate details which are included in "issues" and even numerous PRs.  I'm speaking as a spectator of ESCMI/CIME and my many unread threads in it.

**Comment by billsacks** [comment]
@cacraigucar When we talked earlier, I said I agreed with your last comment. However, I just talked with @bertinia and she reminded me of the key point that emerged from the earlier discussion: Notifications of new tags would come through this CESM repo. We do not expect much traffic in terms of issues and PRs in this repo: most issues and PRs would belong in individual components' repositories. So we felt that asking people to subscribe to this repository would not generate too much spam.

**Comment by bertinia** [comment]
@fischer-ncar and @bertinia mapped out a perl script together with a cronjob to use the github api to check for new tags and send emails accordingly based on tag type (alpha or beta).
We can use the same tool for CLM or MOSART or etc... notification updates as well.

**Comment by ekluzek** [comment]
@bertinia thanks for putting that together! For CLM (really CTSM) we'll want email sent out to clm-dev@cgd.ucar.edu whenever tags are made in ESCOMP/ctsm. We won't worry about notices for MOSART or RTM. We were actually talking about this early today. Thanks for updating this.

Right now under subversion email is only sent for trunk tags. Under git, we might want it for any tags, since development branches will be on peoples personal forks. So there normally wouldn't be any branch tags made, unless it's for a release branch and we probably want notification sent out on those.

OK, but one question @bertinia -- currently it sends out the ChangeLog info. in the email. Is that something that still can be done? With the move to git, we will have a ChangeLog only under the doc directory and not at the top level.

**Comment by bertinia** [comment]
@ekluzek - yes, the github API can pull down a specific file, like the ChangeLog, and attach it
to the email.

**Comment by cacraigucar** [comment]
The script needs to be smart enough to just pull the most recent section of the ChangeLog.  We certainly don't want the full file.

**Comment by billsacks** [comment]
> The script needs to be smart enough to just pull the most recent section of the ChangeLog. We certainly don't want the full file.

Presumably that part could be borrowed from the svn-based script?

**Comment by fischer-ncar** [comment]
> Presumably that part could be borrowed from the svn-based script?

Yes, the svn-based script searches for "Tag name:" in the ChangeLog to parse out the part of
the log file that's new.

**Comment by fischer-ncar** [comment]
I have set up a cronjob on svn41/svn42 that sends out emails when a new alpha or beta is created.
