### ISSUE TITLE
Python 2 end of life

### ISSUE THREAD

**Issue by basnijholt** [ESCOMP/CESM#131]
In the README, I read that some components in CESM aren't Python 3 compliant.

In less than one month, Python 2 will reach it's [end of life](https://pythonclock.org/).
That means that *even if* security bugs appear, that that will not be solved.

Also, many numerical packages like [Numpy and Scipy will no longer be maintained](https://python3statement.org/).

It is probably a good time to upgrade the Python 2 only code 👍

**Comment by jedwards4b** [comment]
CIME itself is fuly py3 compliant - this issue should be raised in the git site of the components.

**Comment by billsacks** [comment]
@fischer-ncar as we discussed today: Can you please test to confirm that a fully-coupled CESM case supports python3, and if so, update the README file appropriately?
