### ISSUE TITLE
Add a script that prints version information

### ISSUE THREAD

**Issue by billsacks** [ESCOMP/CESM#132]
An important piece of information that we request via the forums is the model version, from running `git describe` and `manage_externals/checkout_externals --status --verbose`. But I have been finding that users run these from the wrong place or run them incorrectly (e.g., running `checkout_externals --status` and then separately `checkout_externals --verbose`.

I'd like to make it easier for users to provide the correct information (and easier for us to ensure that users have provided the correct information) by adding a simple python script in the top level of CESM called something like `describe_version`. This script (which would not accept any arguments, other than `--help`) would:
- change to the directory where the script resides (to ensure that the following commands work properly)
- run `git describe`
- run `manage_externals/checkout_externals --status --verbose`

I'd like to add this to both master and the cesm2.1 release branches.

@jedwards4b @mvertens does this make sense to you? Let me know if you have any thoughts on the details.

**Comment by jedwards4b** [comment]
Sure
