### ISSUE TITLE
RUN_TYPE and GET_REFCASE wrong for SSP extensions

### ISSUE THREAD

**Issue by ekluzek** [ESCOMP/CESM#148]
### Summary of Issue:

RUN_TYPE and GET_REFCASE are wrong fro the SSP extensions

### Expected behavior and actual behavior: 

RUN_TYPE is startup but should be hybrid
and GET_REF_CASE is FALSE, but should be TRUE

### Steps to reproduce the problem. Include externals description file(s) and link to public repository):

Setup a case for: BWSSP585extcmip6, BWSSP534osextcmip6, or BWSSP126extcmip6

### What is the changeset ID of the code, and the machine you are using:

cesm2.1.4-rc.01

on cheyenne, but machine doesn't matter.

**Comment by ekluzek** [comment]
GET_REFCASE isn't being set to TRUE for most cases. It seems like it should be for cases when REFCASE is set. I'm adding changes that set GET_REFCASE to TRUE when these particular compsets are triggered, but it seems like it should be more general than that.

@jedwards4b and @fischer-ncar can you comment on this? Should GET_REFCASE be set more generally? Or just for these extension compsets? Or should I leave GET_REFCASE like it is?

**Comment by jedwards4b** [comment]
GET_REFCASE should only be true for the specific compsets that have refcases in inputdata, do not set it in general or we will be getting lots of requests for data that isn't there.

**Comment by ekluzek** [comment]
Well my point is that there's a ton of specific settings for specific REFCASES that are NOT setting GET_REFCASE to TRUE and seem like they should. For here I'm just adding these specific REFCASES for GET_REFCASE, but it seems like these other REFCASES should set it as well. I don't mean a general setting for everything, but for the specific compsets that do set a REFCASE.

**Comment by ekluzek** [comment]
Looks like this was merged, so closing.
