### ISSUE TITLE
I2000Clm50SpRsGs + GLACIER_REGION

### ISSUE THREAD

**Issue by pnlfang** [ESCOMP/CESM#159]
I'm running a global case using compset I2000Clm50SpRsGs. The model has the following error:
  ERROR: GLACIER_REGION NOT on surfdata fileERROR in glcBehaviorMod.F90 at line 583.  I checked a couple of surfdata and didn't find a variable named GLACIER_REGION.  Is there such a surfdata available?  

Is there a compset that only use DATM and lnd similar to previous ICLM45?  I don't need other components.  Thanks!

**Comment by jedwards4b** [comment]
This is a ctsm issue https://github.com/ESCOMP/CTSM it would be best to ask in the cesm forum http://forum.cgd.ucar.edu/

**Comment by billsacks** [comment]
@pnlfang -  Thanks for posting to the forums (https://bb.cgd.ucar.edu/cesm/threads/i2000clm50sprsgs-glacier_region.5332/). I'll continue the discussion there.
