### ISSUE TITLE
checkout_externals should have include/exclude options 

### ISSUE THREAD

**Issue by jedwards4b** [ESCOMP/cesm#16]

**Comment by gold2718** [comment]
+1 but I think this issue should moved to NCAR/manage_externals.

**Comment by jedwards4b** [comment]
Moved - but this is going to be really confusing people to know where to open issues isn't it?
https://github.com/NCAR/manage_externals/issues/62

**Comment by gold2718** [comment]
Yes, and we will probably have to develop some tools to aid the process once CESM2 is released. 
Users will probably open issues either here or on the CGD forum and we will have to manage them. A quick search showed that github doesn't provide an easy way to move issues. There have been some tools which use the github API to do this but you have to give them access to your github accounts which makes me nervous.

**Comment by billsacks** [comment]
@gold2718 I have successfully used https://github-issue-mover.appspot.com/ to move issues. It looks like you can revoke access after using it (via your github account: settings: applications: authorized oauth apps) if that helps you feel more comfortable....

**Comment by billsacks** [comment]
You could also try a CLI tool like https://github.com/buildo/gh-issue-mover if that makes you more comfortable with access permissions.
