### ISSUE TITLE
SLURM walltime computation error

### ISSUE THREAD

**Issue by markyoder** [ESCOMP/CESM#186]
### Brief summary of bug

Get an error computing default SLURM wall time request. Not handling a "{days}-{hours}..." format correctly.

[Give a one or two sentence summary. This could be the same as the issue title if you feel that is a sufficient summary.]

### General bug information

**CESM version you are using:** [Output of `git describe`] v2.2.0

**Machine you are using:** [Fill this in]
CentOS-7; Stanford's Sherlock HPC, 

**Have you modified the code? (If so, please point us to you changes.):** [Yes / No]
No.
Not yet.

### Details of bug

[Fill in details here.]

### Steps to reproduce the problem. Include externals description file(s) and link to public repository
Following a standard "quick start", I get this output:
```

Traceback (most recent call last):
  File "/scratch/users/myoder96/CESM/cesm_sandbox/cime/scripts/create_newcase", line 243, in <module>
    _main_func(__doc__)
  File "/scratch/users/myoder96/CESM/cesm_sandbox/cime/scripts/create_newcase", line 230, in _main_func
    case.create(casename, srcroot, compset, grid, user_mods_dir=user_mods_dir,
  File "/scratch/users/myoder96/CESM/cesm_sandbox/cime/scripts/Tools/../../scripts/lib/CIME/case/case.py", line 1634, in create
    self.configure(compset_name, grid_name, machine_name=machine_name,
  File "/scratch/users/myoder96/CESM/cesm_sandbox/cime/scripts/Tools/../../scripts/lib/CIME/case/case.py", line 1123, in configure
    env_batch.set_job_defaults(bjobs, self)
  File "/scratch/users/myoder96/CESM/cesm_sandbox/cime/scripts/Tools/../../scripts/lib/CIME/XML/env_batch.py", line 272, in set_job_defaults
    seconds = convert_to_seconds(walltime)
  **File "/scratch/users/myoder96/CESM/cesm_sandbox/cime/scripts/Tools/../../scripts/lib/CIME/utils.py", line 1284, in convert_to_seconds
    result += int(component) * pow(60, idx + starting_exp)
ValueError: invalid literal for int() with base 10: '7-00'**
```

I assume this is assuming an HH:MM:SS format (which I prefer too!)

### Screen output or log file showing the error message and context

[Fill this in with anything relevant that you haven't already noted; if there is nothing to add, delete this section.]

**Comment by markyoder** [comment]
Actually.. I think I found this in the configuration. But would it be a terrible idea to write code to recognize a format?

**Comment by jedwards4b** [comment]
I'm not sure that I understand your comment - We welcome contributions from the community if you have a better solution.

**Comment by markyoder** [comment]
Sorry guys; that came out wrong. I meant to ask if it would be difficult to write a little pattern detection script. Obviously, not tough in principle, but they can cause conflicts, or make things not break when they should break.
