### ISSUE TITLE
Collecting the advice of @alperaltuntas from multiple comments earlier in the thread into 1 place:

### ISSUE THREAD

**Issue by s449f** [ESCOMP/CESM#198]
Collecting the advice of @alperaltuntas from multiple comments earlier in the thread into 1 place:
Does the command `which csh` return any path? If not, you will have to install csh.
It may be available via a module in your local machine.
Once it is installed, check to see if it is present at the location `/bin/csh`
by running the command `ls -lF /bin/csh`.
If it is not there, copy it there by running the command
```
cp `which csh` /bin/csh
```

_Originally posted by @klindsay28 in https://github.com/ESCOMP/CESM/issues/74#issuecomment-998821623_

**Comment by billsacks** [comment]
It looks like you might have opened this new issue by accident? I'm going to close it but feel free to reopen if you feel there is a real issue.
