### ISSUE TITLE
Fold cime_config into this repository

### ISSUE THREAD

**Issue by billsacks** [ESCOMP/cesm#21]
As decided in #20 , we should fold https://github.com/cesm-development/cime_config into this repository.

**Comment by billsacks** [comment]
@fischer-ncar @bertinia I'm tentatively assigning both of you to this, since I think you will be most heavily impacted (@bertinia through changes in the testdb), so I want to let you do it at a time that's convenient. I'm happy to help with the actual git migration, though, if you'd like. In particular, it would be good for this be done in a way that maintains history.

**Comment by fischer-ncar** [comment]
I've updated the testdb to reflect the changes for the cime_config move.  So @bertinia doesn't have to worry about this.  

The move is going to happen in cesm2_0_alpha10b.  I wanted to clean up some issues and pull request first.

**Comment by billsacks** [comment]
@fischer-ncar great, thanks! Let me know if you could use any help with the move.
