### ISSUE TITLE
cesm2_1 cmip6 refcase at f19_g17

### ISSUE THREAD

**Issue by jedwards4b** [ESCOMP/CESM#214]
### Brief summary of bug

The compset f19_g17.B1850cmip6 should have a refcase in the cesm2.1.x release, it does not. 

### General bug information

**CESM version you are using:** cesm2.1.4-rc.11-1-g0b23ba0

**Machine you are using:**  cheyenne

**Have you modified the code? (If so, please point us to you changes.):**  No

### Details of bug

A refcase should be defined for this.  I tested with 
./xmlchange GET_REFCASE=TRUE
./xmlchange RUN_TYPE=hybrid
./xmlchange RUN_REFCASE=b.e21.B1850.f19_g17.CMIP6-piControl-2deg.001
./xmlchange RUN_REFDATE=0281-01-01
and it works.   Is this the correct one though?

### Steps to reproduce the problem. Include externals description file(s) and link to public repository

Can be reproduced with SMS.f19_g17.B1850cmip6

**Comment by ekluzek** [comment]
Closing as a WONTFIX since our concern for CESM2.1 isn't large enough to look into this.
