### ISSUE TITLE
Need new BLT1850_v0b and BMT1850v0b compsets

### ISSUE THREAD

**Issue by fischer-ncar** [ESCOMP/CESM#222]
@cacraigucar @adamrher 
We need B1850 to invoke the config options in FLTHIST_v0b / FMTHIST_v0b (maybe BLT1850_v0b / BMT1850_v0b?), and in addition it should update to CLM51%BGC-CROP

**Comment by fischer-ncar** [comment]
@adamrher, what resolution will these runs be at?  I would like to add a couple of tests for the new compset.

**Comment by billsacks** [comment]
> BLT1850

Mmmm, sounds like a delicious compset!

**Comment by adamrher** [comment]
The grid alias we've been using is ```ne30pg3_t061```. But I also want to bring @gustavo-marques in this discussion, as he had discussed potentially changing the grid alias to reflect his "new" mom6 grid.

haha, yes, a 150+ year old BLT

**Comment by adamrher** [comment]
@fvitt -- since this will be an 1850 case, we need to find an LBC file is appropriate for CAM%DEV%LT%GHGMAM4

**Comment by fischer-ncar** [comment]
So this is using mom.  So the long name should look like this.

1850_CAM%DEV%LT%GHGMAM4_CLM51%BGC-CROP_CICE_MOM6_MOSART_CISM2%GRIS-NOEVOLVE_WW3_BGC%BDRD
1850_CAM%DEV%MT%GHGMAM4_CLM51%BGC-CROP_CICE_MOM6_MOSART_CISM2%GRIS-NOEVOLVE_WW3_BGC%BDRD

**Comment by fischer-ncar** [comment]
I just tried running a couple of smoke tests for the new compsets, and got the following errors.

SMS.ne30pg3_t061.BLT1850_v0b.cheyenne_intel
 ERROR: ADDFLD:  CO2_fvm already on list

SMS.ne30pg3_t061.BMT1850_v0b.cheyenne_intel
 ERROR: ADDFLD:  CO2_fvm already on list

**Comment by klindsay28** [comment]
I suspect that `-chem ghg_mam4` and `-co2_cycle` in `CAM_CONFIG_OPTS` are not playing friendly with each other.
These options together are turning on multiple copies of `CO2`, leading to a collision when defining history variables.
There's some harmonization of these options that needs to happen, but hasn't been implemented yet.
Can you try omitting the `_BGC%BDRD` suffix on the long name?
I think that will turn off `-co2_cycle`.

**Comment by fischer-ncar** [comment]
My smoke tests passed after removing ```_BGC%BDRD```
