### ISSUE TITLE
bad pelayout for cheyenne

### ISSUE THREAD

**Issue by jedwards4b** [ESCOMP/CESM#228]
### Brief summary of bug
The pelayout here https://github.com/ESCOMP/CESM/blob/master/cime_config/config_pes.xml#L404 incorrectly overlaps ocn and ice components and is very slow.   I think that there is a typo and changing NTASKS_LND=NTASKS_ROF=ROOTPE_ICE=720 will solve the problem.

### General bug information

**CESM version you are using:** master (2227a51)

**Machine you are using:** cheyenne

**Have you modified the code? (If so, please point us to you changes.):** No

### Details of bug

above

### Steps to reproduce the problem. Include externals description file(s) and link to public repository

[Fill this in with anything relevant that you haven't already noted; if there is nothing to add, delete this section.]

### Screen output or log file showing the error message and context

[Fill this in with anything relevant that you haven't already noted; if there is nothing to add, delete this section.]

**Comment by jedwards4b** [comment]
@fischer-ncar FYI

**Comment by fischer-ncar** [comment]
@jedwards4b working on this when cheyenne went down.  I agree that it's a typo.  But I want to run a couple of quick tests.

**Comment by fischer-ncar** [comment]
@jedwards4b 
I tried changing NTASKS_LND, NTASKS_ROF, and ROOTPE_ICE to 720 but didn't see much of a difference.

Original pes layout with NTASKS_LND=NTASKS_ROF=ROOTPE_ICE=724

>     
    TOT Run Time:     322.387 seconds       64.477 seconds/mday         3.67 myears/wday 
    CPL Run Time:       7.090 seconds        1.418 seconds/mday       166.94 myears/wday 
    ATM Run Time:     119.574 seconds       23.915 seconds/mday         9.90 myears/wday 
    LND Run Time:      10.581 seconds        2.116 seconds/mday       111.86 myears/wday 
    ICE Run Time:      15.116 seconds        3.023 seconds/mday        78.30 myears/wday 
    OCN Run Time:     316.298 seconds       63.260 seconds/mday         3.74 myears/wday 
    ROF Run Time:       0.195 seconds        0.039 seconds/mday      6066.44 myears/wday 
    GLC Run Time:       0.000 seconds        0.000 seconds/mday         0.00 myears/wday 
    WAV Run Time:       8.160 seconds        1.632 seconds/mday       145.04 myears/wday 
    ESP Run Time:       0.000 seconds        0.000 seconds/mday         0.00 myears/wday 
    CPL COMM Time:    157.418 seconds       31.484 seconds/mday         7.52 myears/wday 

Then with NTASKS_LND=NTASKS_ROF=ROOTPE_ICE=720

>     
    TOT Run Time:     325.840 seconds       65.168 seconds/mday         3.63 myears/wday 
    CPL Run Time:       6.939 seconds        1.388 seconds/mday       170.56 myears/wday 
    ATM Run Time:     119.697 seconds       23.939 seconds/mday         9.89 myears/wday 
    LND Run Time:      11.562 seconds        2.312 seconds/mday       102.37 myears/wday 
    ICE Run Time:      14.831 seconds        2.966 seconds/mday        79.80 myears/wday 
    OCN Run Time:     316.262 seconds       63.252 seconds/mday         3.74 myears/wday 
    ROF Run Time:       0.169 seconds        0.034 seconds/mday      7007.47 myears/wday 
    GLC Run Time:       0.000 seconds        0.000 seconds/mday         0.00 myears/wday 
    WAV Run Time:       8.582 seconds        1.716 seconds/mday       137.92 myears/wday 
    ESP Run Time:       0.000 seconds        0.000 seconds/mday         0.00 myears/wday 
    CPL COMM Time:    160.432 seconds       32.086 seconds/mday         7.38 myears/wday 

I also tried changing the task count for the ocn.  But only succeeded in making things slower.
What kind of performance are you expecting?

**Comment by jedwards4b** [comment]
Can you point me to these directories please.  In the first decomposition 724+1080 = 1804 which means that the cice and ocn tasks overlap and should be much slower than the corrected configuration.

**Comment by jedwards4b** [comment]
MOOT - cheyenne is retired
