### ISSUE TITLE
Need to change describe_version script for manage_externals replacement

### ISSUE THREAD

**Issue by billsacks** [ESCOMP/CESM#245]
The top-level describe_version script is meant to provide information that can help us see the exact model version that people are using when they submit a help request. This currently leverages manage_externals and will need to be updated for @jedwards4b 's replacement for manage_externals.

**Comment by jedwards4b** [comment]
I think that git-fleximod status gives the same information.

**Comment by billsacks** [comment]
I can make this change once git-fleximod replaces manage_externals.
