### ISSUE TITLE
Build machine example of AMD 4th zen cpu

### ISSUE THREAD

**Issue by cron-weasley** [ESCOMP/CESM#259]
Dear developer, 
Do we have some example machine file or suggest of build cesm2.3 with amd zen4 cpu such as amd epyc9654X(avx512) with aocc and aocl or gcc13.2? 
Thanks!

**Comment by jedwards4b** [comment]
Not with aocc and aocl but derecho should serve as an example with gcc.

**Comment by cron-weasley** [comment]
> Not with aocc and aocl but derecho should serve as an example with gcc.

thanks for your quick reply， and if use gcc, which version of netcdf netcdf-fortran and hdf5 do we perfer？

**Comment by jedwards4b** [comment]
You will also find those in the machine definition for derecho - [here ](https://github.com/ESMCI/ccs_config_cesm/blob/main/machines/derecho/config_machines.xml)

**Comment by cron-weasley** [comment]
> You will also find those in the machine definition for derecho - [here ](https://github.com/ESMCI/ccs_config_cesm/blob/main/machines/derecho/config_machines.xml)

Thanks a lot for your help!   ;)
