### ISSUE TITLE
Please update manage_externals

### ISSUE THREAD

**Issue by jedwards4b** [ESCOMP/cesm#35]

**Comment by jedwards4b** [comment]
@fischer-ncar please add this to your next cesm tag for 2.0, 2.1 and 2.2.

**Comment by fischer-ncar** [comment]
I've updated manage_externals(v1.1.5) for the 2.0, 2.1 alpha branches, and 2.2 master. 
The future cesm tags that will have v1.1.5 are

* cesm2.0.2-rc.01, if there is one.
* cesm2_1_alpha01b
* cesm2_2_alpha01b
