### ISSUE TITLE
Add status writes to manage_externals

### ISSUE THREAD

**Issue by cacraigucar** [ESCOMP/cesm#4]
Going from a git or svn checkout where the screen is inundated with every file checked out, to manage_externals where it silently sits there for minutes can be disconcerting as you are not sure if the command is making progress or not.  A simple "starting to check out XXX", "completed check out of XXX" for each of the components would be useful so the user can make sure progress is actually being made. I ended up opening a new window and seeing that something was happening just to make sure progress was being made and it wasn't simply hung.

**Comment by billsacks** [comment]
This issue was moved to NCAR/manage_externals#28

**Comment by billsacks** [comment]
@cacraigucar Issues specific to the manage_externals tool should go in https://github.com/NCAR/manage_externals/ . I know this is a bit confusing, so don't at all fault you for putting these issues here - just letting you know for the future. (Although I'll also note that manage_externals might move its home to ESMCI or elsewhere....)
