### ISSUE TITLE
Get rid of ">" in quick start instructions?

### ISSUE THREAD

**Issue by billsacks** [ESCOMP/cesm#50]
I feel that the ">" at the start of shell commands in the quick start instructions is more troublesome than helpful, because it means you can't copy and paste commands. At least one other person (I think it was Cecile Hannay, but I may be wrong) felt the same way. This is a low-priority cleanup fix, but would be nice to do if others agree.

@bertinia are you attached to these ">" characters?

**Comment by gold2718** [comment]
In the past, there have been issues raised by unexpected behavior when cutting and pasting including (at least) one case where the instructions included a special character that looked like a space but was not recognized by bash.
