### ISSUE TITLE
update Quickstart with release tag clone command

### ISSUE THREAD

**Issue by bertinia** [ESCOMP/cesm#54]
The [Downloading the CESM2 Code](http://www.cesm.ucar.edu/models/cesm2.0//release_download.html) page includes
clone instruction with a generic branch name "release2.0". The idea is to have
the release2.0 branch point to the most current, officially supported code base. 
For example, the initial release2.0 branch would point to CESM2.0.0 tag; when
CESM2.0.1 tag is available, the release2.0 branch would be updated in the repo BUT
the documentation could remain the same. 

This will require `git describe` instructions be added for how to check the code version in 
a users cloned sandbox.

**Comment by billsacks** [comment]
A related change that should be made here is that we should remove the information about svn authentication using guestuser, since I think that won't be required, right?
