### ISSUE TITLE
Problems running manage_externals when updating along the cesm2.0 release branch

### ISSUE THREAD

**Issue by billsacks** [ESCOMP/cesm#64]
### Summary of Issue:

I had a clone of the cesm repo, with all externals checked out via `manage_externals` (I'm not sure what version of cesm I was at originally - sorry). Then I updated to the latest version of master (2c75ae5). When I reran `./manage_externals/checkout_externals`, I got errors like this:

```
Checking out externals: clm, mosart, ww3, cime, cice, pop, ERROR:root:Command '[u'svn', u'switch', u'--quiet', u'https://svn-ccsm-models.cgd.ucar.edu/pop2/release_tags/pop2_cesm2_0_rel_n02']' returned non-zero exit status 1
ERROR:root:Failed with output:
    svn: E195012: Path '.' does not share common version control ancestry with the requested switch location.  Use --ignore-ancestry to disable this check.
    svn: E195012: 'https://svn-ccsm-models.cgd.ucar.edu/pop2/release_tags/pop2_cesm2_0_rel_n02' shares no common ancestry with '/Users/sacks/cesm_code/cesm/components/pop'

ERROR: In directory
    /Users/sacks/cesm_code/cesm/components/pop
Process did not run successfully; returned status 1:
    svn switch --quiet https://svn-ccsm-models.cgd.ucar.edu/pop2/release_tags/pop2_cesm2_0_rel_n02
See above for output from failed command.
Please check the log file manage_externals.log for more details.

ERROR: Failed with output:
    svn: E195012: Path '.' does not share common version control ancestry with the requested switch location.  Use --ignore-ancestry to disable this check.
    svn: E195012: 'https://svn-ccsm-models.cgd.ucar.edu/pop2/release_tags/pop2_cesm2_0_rel_n02' shares no common ancestry with '/Users/sacks/cesm_code/cesm/components/pop'

ERROR: In directory
    /Users/sacks/cesm_code/cesm/components/pop
Process did not run successfully; returned status 1:
    svn switch --quiet https://svn-ccsm-models.cgd.ucar.edu/pop2/release_tags/pop2_cesm2_0_rel_n02
See above for output from failed command.
Please check the log file manage_externals.log for more details.
```

I worked around this by doing `rm -rf components/pop` then rerunning `./manage_externals/checkout_externals`. This gave a similar error for cam, which I again worked around with `rm -rf components/cam`. Then it worked.

**Comment by billsacks** [comment]
We could work around this by adding `--ignore-ancestry` in the `svn switch` command in `manage_externals`. I'm a bit hesitant to do that because it could mask true issues (in general, it seems like trying to svn switch to a URL that doesn't share ancestry is a Bad Idea).

I don't understand why these CAM and POP release tags don't share ancestry with older release tags. Is it possible that they were created incorrectly? Or is this a natural consequence of the way we create svn release tags? If this is something that is going to arise again, I guess we should change manage_externals.

**Comment by jedwards4b** [comment]
I think that this problem occurs rarely and the solution should just be to remove the problem components and run checkout_externals again.  Otherwise we may need to deal with unintended consequences of using the --ignore-ancestry flag, which I think could be worse than the current problem.

**Comment by billsacks** [comment]
I'm fine closing this as a wontfix, at least until it starts tripping people up a lot.
