### ISSUE TITLE
release-clm5.0.01 seems to be a "private repository"

### ISSUE THREAD

**Issue by kdraeder** [ESCOMP/cesm#72]
When I try to build a CAM6 from the released CESM2_0,
or update the components using 
$> ./manage_externals/checkout_externals it fails when dealing with CLM 
(https://github.com/ESCOMP/ctsm:release-clm5.0.01)
with the message:
> Checking status of externals: clm, ERROR:root:
>     subprocess call to  'git' has exceeded timeout limit of 300 seconds.
> Timout errors typically occur when svn or git requires
> authentication to access a private repository. ...
When running case.build, I can add --skip-provenance-check
and it builds.  But I'm not aware of a way to do a similar thing
when running checkout_externals.  And it seems like such a 
kluge shouldn't be necessary.
The directory where this is happening is
/gpfs/fs1/work/raeder/Models/cesm2_0,
which has a few untracked files, but nothing added or committed.

**Comment by billsacks** [comment]
This seems to be a manage_externals issue. I'm going to move this to the manage_externals issue tracker and add more information there.

**Comment by billsacks** [comment]
This issue was moved to ESMCI/manage_externals#113
