### ISSUE TITLE
Do we still need the b1850 usermods directory?

### ISSUE THREAD

**Issue by billsacks** [ESCOMP/cesm#77]
Is the b1850 usermods directory still needed? It contains https://github.com/ESCOMP/cesm/blob/master/cime_config/usermods_dirs/b1850/user_nl_cpl

It was added in https://github.com/CESM-Development/cime_config/pull/44, but I can't find notes about why it was needed then.

@jedwards4b @mvertens any idea?

If it isn't needed any more, I was thinking we should remove it to keep the usermods directories limited to important things like the cmip6 usermods.

**Comment by billsacks** [comment]
If I'm reading

https://github.com/ESMCI/cime/blob/e002ac34ba44c87a2c121325a48c1c6b67a37a64/src/drivers/mct/cime_config/namelist_definition_drv.xml#L447-L475

correctly, it looks like this shouldn't be needed any more for CESM, but can someone confirm?

**Comment by jedwards4b** [comment]
I don't believe that this user_mod is needed any longer - you can confirm with a quick test.

**Comment by billsacks** [comment]
I have confirmed that the drv_in is identical with and without this usermods for B1850, in both master and cesm2.1-alphabranch. I'll put in PRs to remove it in both places.
