### ISSUE TITLE
Change CESM.cfg to be alphabetical order

### ISSUE THREAD

**Issue by bertinia** [ESCOMP/cesm#9]
Would it be possible to store the CESM.cfg file components in alphabetical order? This
would help with the testdb display when comparing the component info stored in the database
with what is in the CESM.cfg file. Here's what is displayed from the database:

[cam]
tag = trunk_tags/cam5_4_143/components/cam
protocol = svn
repo_url = https://svn-ccsm-models.cgd.ucar.edu/cam1
local_path = components/cam
required = True

[cice]
tag = cice5_20170927
protocol = svn
repo_url = https://svn-ccsm-models.cgd.ucar.edu/cice/trunk_tags/cice5_20170927
local_path = components/cice
required = True

[cime]
tag = cime5.4.0-alpha.11
protocol = git
repo_url = https://github.com/ESMCI/cime/releases/tag/cime5.4.0-alpha.11
local_path = cime
required = True

[cime_config]
tag = cime_config0.1.0.alpha.05
protocol = git
repo_url = https://github.com/CESM-Development/cime_config/releases/tag/cime_config0.1.0.alpha.05
local_path = cime_config
required = True

[cism]
tag = trunk_tags/cism2_1_40
protocol = svn
repo_url = https://svn-ccsm-models.cgd.ucar.edu/glc
local_path = components/cism
required = True

[clm]
tag = 
protocol = svn
repo_url = https://svn-ccsm-models.cgd.ucar.edu/clm2
local_path = components/clm
required = True

[mosart]
tag = branch_tags/mosart1_0_26_cimeupdates_tags/n01
protocol = svn
repo_url = https://svn-ccsm-models.cgd.ucar.edu/mosart
local_path = components/mosart
required = True

[pop]
tag = cesm_pop_2_1_20171117
protocol = svn
repo_url = https://svn-ccsm-models.cgd.ucar.edu/pop2/trunk_tags/cesm_pop_2_1_20171117
local_path = components/pop
required = True

[rtm]
tag = branch_tags/rtm1_0_62_cimeupdate_tags/n01
protocol = svn
repo_url = https://svn-ccsm-models.cgd.ucar.edu/rivrtm
local_path = components/rtm
required = True

[ww3]
tag = trunk_tags/ww3_170731
protocol = svn
repo_url = https://svn-ccsm-models.cgd.ucar.edu/ww3
local_path = components/ww3
required = True

[externals_description]
schema_version = 1.0.0

**Comment by ekluzek** [comment]
@bertinia if you need it in alphabetical order, the script should probably not just allow it, but check for it and require it.

**Comment by bertinia** [comment]
@ekluzek - this is just for display purposes in order to compare side-by-side results between what is stored in the testdb vs. what in master/CESM.cfg.  

The testdb app reads the externals fields into a hash with no order imposed. In the display template, I sort on the hash keys and display them in alphabetical order. The testdb app then reads the master version of the CESM.cfg using the github API. The API returns a JSON message with the CESM.cfg data encoded base64. The decoded CESM.cfg file displays directly on the web page as it was read with no sorting.

**Comment by bertinia** [comment]
This issue is handled by updates from the testdb.
