### ISSUE TITLE
Future scenario period names in compset longnames need to change

### ISSUE THREAD

**Issue by ekluzek** [ESCOMP/cesm#97]
### Summary of Issue:

CMIP5 future scenario names which are currently in compset longnames are based on the four standard RCP's: 8.5, 6.0, 4.5, 2.6. The CMIP6 future scenarios are SSP (Shared Socioeconomic Pathway) RCP (Representative concentration Pathway) combinations, usually expressed as SSP#-#.# for the SSP number, and RCP concentration. 

### Expected behavior and actual behavior:

The only recognized future scenario's are RCP[2468]. We need something like SSP[12345][123468], which is a minimum of five digits for it rather than the usual four.

The entire list is:

SSP5-RCP8.5
SSP1-RCP2.6
SSP3-RCP7.0
SSP5-RCP3.4
SSP2-RCP4.5  
SSP1-RCP1.9
SSP4-RCP3.4
SSP4-RCP6.0

**Comment by fvitt** [comment]
Is this the convention we are following?

So the WACCM SSP585 compset would be as follows?

  <compset>
    <alias>BWSSP585cmip6</alias>

<lname>SSP5-RCP8.5_CAM60%WCTS_CLM50%BGC-CROP-CMIP6WACCMDECK_CICE%CMIP6_POP2%ECO%NDEP_MOSART_CISM2%NOEVOLVE_WW3</lname>
  </compset>

**Comment by ekluzek** [comment]
@fvitt I think we should use: SSP#-#.#. That's the form that is normally used (so RCP is implied for the second number).

So it would be...

``` xml
<compset> <alias>BWSSP585</alias>

<lname>SSP5-8.5_CAM60%WCTS_CLM50%BGC-CROP-CMIP6WACCMDECK_CICE%CMIP6_POP2%ECO%NDEP_MOSART_CISM2%NOEVOLVE_WW3</lname>
```

That's what I think. But, the main thing is to make sure we pick a convention and stick to it.

**Comment by fvitt** [comment]
This could also be shortened to:

<lname>SSP585_CAM60%WCTS_CLM50%BGC-CROP-CMIP6WACCMDECK_CICE%CMIP6_POP2%ECO%NDEP_MOSART_CISM2%NOEVOLVE_WW3</lname>

**Comment by ekluzek** [comment]
I think the dash is helpful though in making it easier to read. I like leaving off RCP since it only makes it longer and SSP#-#.# is still the convention. I think we used to be limited to four characters, but I don't think there is such a limit anymore. So adding a character to increase readability seems good to me. But, that's all IMHO.

**Comment by bertinia** [comment]
I think the compset long names should match what is in the WRCP CMIP6 experiments controlled vocabulary. 

https://github.com/WCRP-CMIP/CMIP6_CVs/blob/master/CMIP6_experiment_id.json

This will hopefully avoid confusion between CESM experiments defined by compsets and other modeling center experiment configurations that don't use the same naming convention as CESM compsets and data organization in the ESGF archive.

**Comment by jedwards4b** [comment]
I'm not sure that the . and - characters are allowed - are you?

**Comment by kauff** [comment]
I think the RCP is the dominant forcing/feature, and it's already familiar from previous releases, while the SSP denotes a relatively minor variation on the forcing.   So that RCP85-1 makes more sense than SSP1-85     But if WRCP CMIP6 already does it the other way around, consistency is probably the best option.

**Comment by ekluzek** [comment]
@kauff I checked with a couple of the scientists about the SSP-RCP combination. The standard convention is to put SSP first. And Peter Lawrence felt it makes the most sense that way. The emissions result from the SSP setup. There are some cases where one SSP can result in more than one RCP, but it can't span the spectrum. SSP1 doesn't result in RCP8.5 no matter what for example. Since, that convention is well established I think we should follow it.

**Comment by ekluzek** [comment]
@jedwards4b I know dashes work, because we use them for CLM with things like CLM50%BGC-CROP.  Looking in cime in utils.py for check_name the following are NOT allowed: +*?<>/{}[\]~`@:. So dash and . would be allowed.

**Comment by jedwards4b** [comment]
DIdn't @fvitt decide this by checking in waccm compsets with names 
```
<compset>
    <alias>BWSSP585cmip6</alias>
    <lname>SSP5-8.5_CAM60%WCTS_CLM50%BGC-CROP-CMIP6WACCMDECK_CICE%CMIP6_POP2%ECO%NDEP_MOSART_CISM2%NOEVOLVE_WW3</lname>
  </compset>

  <compset>
    <alias>BWSSP534oscmip6</alias>
    <lname>SSP5-3.4_CAM60%WCTS_CLM50%BGC-CROP-CMIP6WACCMDECK_CICE%CMIP6_POP2%ECO%NDEP_MOSART_CISM2%NOEVOLVE_WW3</lname>
  </compset>
```

**Comment by fvitt** [comment]
We can change it if a different naming convention is prefered

**Comment by ekluzek** [comment]
I'm fine with the convention that @fvitt has here.

SSP#-#.#_

I just wanted to make sure it was set! So I'll use that form in CTSM.

**Comment by ekluzek** [comment]
@jedwards4b verified that the long names don't work with a period. We thought they would because of the list in check_name. I think it fails because of this though...

`case.py:        expect(check_name(compset_name, additional_chars='.'), "Invalid compset name {}".format(compset_name))`


So it explicitly adds a "." as an additional character that can't be used in a compset name. Apparently this works if the alias doesn't have a period (although it would fail if you had a period in the alias name).

**Comment by ekluzek** [comment]
The convention that Cheryl and I are moving forward with is to remove the dot and dashes. So SSP585 for example. @bertinia this is closer to the WRCP standard, I think the only difference is uppercase vs. lowercase. This means that @fvitt will need to change what he put in place for CAM-WACCM as well as @alperaltuntas for POP.
